apiVersion: batch/v1
kind: Job
metadata:
  name: testkube-postsync-hook
  namespace: testkube
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: run-tests
          image: kubeshop/testkube-cli:latest
          command: [/bin/sh, -c]
          args:
            - |
              set -e
              echo "Executing Hurl API test workflow..."
              testkube -a http://testkube-api-server.testkube.svc.cluster.local:8088 -c direct run tw api-hurl-workflow -f
              
              echo "Executing Cypress Web test workflow..."
              testkube -a http://testkube-api-server.testkube.svc.cluster.local:8088 -c direct run tw web-cypress-workflow -f
      restartPolicy: Never
  backoffLimit: 0
