apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: api-hurl-workflow
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/finn-e/testkube-samples.git
      revision: main
  steps:
    - name: run-hurl-tests
      run:
        image: ghcr.io/orange-opensource/hurl:latest
        args:
          - --test
          - /data/repo/apps/api/tests/app.hurl
          - --variable
          - origin=http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
